baseURL = "https://unlogic.co.uk/"
languageCode = "en-us"
title = "Unlogic"
theme = "m10c"
paginate = 10
summarylength = 10


# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Unlogic"
author = "Sven Steinbauer"
description = "I have a keyboard, a terminal, and a whole load of luck"
avatar = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true
displayMode = "dark"

[params.style]
  darkestColor = "#315659"
  darkColor = "#253031"
  lightColor = "#96a879"
  lightestColor = "#fff"
  primaryColor = "#dad865"

[[params.social]]
icon = "github"
title = "GitHub"
url = "https://github.com/Svenito/"

[[params.social]]
icon = "gitlab"
title = "GitLab"
url = "https://gitlab.com/unlogic"
